openach/urls.py
"""Analysis of Competing Hypotheses Django Application URL Configuration.

See the Django documentation for more information:
* https://docs.djangoproject.com/en/2.1/ref/urls/
* https://docs.djangoproject.com/en/2.1/topics/http/urls/
"""

from django.urls import path

from . import views

# NOTE: Django's API doesn't follow constant naming convention for 'app_name' and 'urlpatterns'

app_name = "openach"  # pylint: disable=invalid-name

urlpatterns = [  # pylint: disable=invalid-name
    path("", views.site.index, name="index"),
    # NOTE: when running the dev server, Django will try to serve from the static file provider b/c of static prefix
    path("static/images/bitcoin.svg", views.site.bitcoin_qrcode, name="bitcoin_donate"),
    path("boards/", views.boards.board_listing, name="boards"),
    path(
        "accounts/<int:account_id>/boards/",
        views.boards.user_board_listing,
        name="user_boards",
    ),
    path(
        "accounts/notifications/clear/",
        views.notifications.clear_notifications,
        name="clear_notifications",
    ),
    path(
        "accounts/notifications/",
        views.notifications.notifications,
        name="notifications",
    ),
    path("teams/create/", views.teams.create_team, name="create_team"),
    path("teams/", views.teams.team_listing, name="teams"),
    path("teams/<int:team_id>/join/", views.teams.join_team, name="join_team"),
    path("teams/<int:team_id>/leave/", views.teams.leave_team, name="leave_team"),
    path("teams/<int:team_id>/", views.teams.view_team, name="view_team"),
    path("teams/<int:team_id>/edit/", views.teams.edit_team, name="edit_team"),
    path("teams/<int:team_id>/members/", views.teams.team_members, name="team_members"),
    path(
        "teams/<int:team_id>/members/invite/",
        views.teams.invite_members,
        name="invite_members",
    ),
    path(
        "teams/<int:team_id>/members/<int:member_id>/revoke/",
        views.teams.revoke_membership,
        name="revoke_membership",
    ),
    path(
        "teams/invitations/<int:invite_id>/",
        views.teams.decide_invitation,
        name="decide_invitation",
    ),
    path("boards/<int:board_id>/", views.boards.detail, name="detail"),
    path("boards/create/", views.boards.create_board, name="create_board"),
    path(
        "boards/<int:board_id>/history/",
        views.boards.board_history,
        name="board_history",
    ),
    path("boards/<int:board_id>/edit/", views.boards.edit_board, name="edit_board"),
    path(
        "boards/<int:board_id>/permissions/",
        views.boards.edit_permissions,
        name="edit_permissions",
    ),
    path(
        "boards/<int:board_id>/evidence/add/",
        views.evidence.add_evidence,
        name="add_evidence",
    ),
    path(
        "evidence/<int:evidence_id>/sources/add/",
        views.evidence.add_source,
        name="add_source",
    ),
    path(
        "evidence/<int:evidence_id>/sources/<int:source_id>/tag/",
        views.evidence.toggle_source_tag,
        name="tag_source",
    ),
    path(
        "evidence/<int:evidence_id>/edit/",
        views.evidence.edit_evidence,
        name="edit_evidence",
    ),
    path(
        "evidence/<int:evidence_id>/",
        views.evidence.evidence_detail,
        name="evidence_detail",
    ),
    path(
        "hypotheses/<int:hypothesis_id>/edit/",
        views.hypotheses.edit_hypothesis,
        name="edit_hypothesis",
    ),
    path(
        "boards/<int:board_id>/hypotheses/add/",
        views.hypotheses.add_hypothesis,
        name="add_hypothesis",
    ),
    path(
        "boards/<int:board_id>/evidence/<int:evidence_id>/evaluate/",
        views.boards.evaluate,
        name="evaluate",
    ),
    path(
        "boards/<int:board_id>/<slug:dummy_board_slug>/",
        views.boards.detail,
        name="detail_slug",
    ),
    path("about/", views.site.about, name="about"),
    # JSON API
    path("api/boards/", views.boards.board_search, name="board_search"),
]

openintel/urls.py
"""Open Synthesis URL Configuration.

See the Django documentation for more information:
* https://docs.djangoproject.com/en/2.1/ref/urls/
* https://docs.djangoproject.com/en/2.1/topics/http/urls/
"""

import notifications.urls
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path, re_path
from django.views.generic import TemplateView

from openach import views
from openach.sitemap import BoardSitemap

ACCOUNT_REQUIRED = getattr(settings, "ACCOUNT_REQUIRED", False)

# NOTE: Django's API doesn't follow constant naming convention for 'sitemaps' and 'urlpatterns'

# https://docs.djangoproject.com/en/1.10/ref/contrib/sitemaps/#initialization
sitemaps = {  # pylint: disable=invalid-name
    "board": BoardSitemap,
}

urlpatterns = [  # pylint: disable=invalid-name
    path("admin/", admin.site.urls),
    path("robots.txt", views.site.robots, name="robots"),
    path(
        "contribute.json",
        TemplateView.as_view(
            template_name="contribute.json", content_type="application/json"
        ),
    ),
    path(
        "accounts/signup/",
        views.site.CaptchaSignupView.as_view(),
        name="account_signup",
    ),
    path("accounts/<int:account_id>/", views.profiles.profile, name="profile"),
    path("accounts/profile/", views.profiles.private_profile, name="private_profile"),
    path("accounts/", include("allauth.urls")),
    path("comments/", include("django_comments.urls")),
    path(
        "inbox/notifications/", include(notifications.urls, namespace="notifications")
    ),
    path("invitations/", include("invitations.urls", namespace="invitations")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("", include("openach.urls")),
    re_path(
        r"\.well-known/acme-challenge/(?P<challenge_key>[a-zA-Z0-9\-_]+)$",
        views.site.certbot,
    ),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns


if not ACCOUNT_REQUIRED:  # pylint: disable=invalid-name
    # Only allow clients to view the sitemap if the admin is running a public instance
    urlpatterns.insert(
        0,
        path(
            r"sitemap.xml",
            sitemap,
            {"sitemaps": sitemaps},
            name="django.contrib.sitemaps.views.sitemap",
        ),
    )  # nopep8

openach/views/allocate_invites.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from notifications.signals import notify

from openach.forms import IssueInviteForm
from openach.models import Invitation

PAGE_CACHE_TIMEOUT_SECONDS = getattr(settings, "PAGE_CACHE_TIMEOUT_SECONDS", 60)


@login_required
@require_http_methods(["POST"])
@transaction.atomic
def issue_invite(request):
    if request.user.invites_remaining <= 0:
        messages.error(request, "You don't have any remaining invites.")
        return HttpResponseRedirect(reverse("openach:index"))

    if request.method == 'POST':
        form = IssueInviteForm(request.POST, request=request)  # Pass the request
        if form.is_valid():
            invitee_email = form.cleaned_data['invitee_email']
            invitation = Invitation.objects.create(
                inviter=request.user,
                invitee_email=invitee_email
            )
            email = create_invitation_email(invitation, request)
            email.send()

            notify.send(request.user, recipient=invitation.invitee, verb='sent an invitation')

            messages.success(request, 'Invitation has been sent!')
            return HttpResponseRedirect(reverse("openach:index"))
    else:
        form = IssueInviteForm(request=request)  # Pass the request

    return render(request, 'boards/invite_form.html', {'form': form})


def create_invitation_email(invitation, request):
    """Return an invitation email message."""
    context = {
        'invitation': invitation,
        'site': get_current_site(request),
        'signup_url': reverse('signup_url')
    }

    subject = render_to_string(
        "boards/email/invitation_subject.txt", context=context
    )
    subject = " ".join(subject.splitlines()).strip()

    text_body = render_to_string(
        "boards/email/invitation_message.txt", context=context
    )
    html_body = render_to_string(
        "boards/email/invitation_message.html", context=context
    )

    email = EmailMultiAlternatives(subject, text_body, settings.DEFAULT_FROM_EMAIL, [invitation.invitee_email])
    email.attach_alternative(html_body, "text/html")
    return email

openach/views/evidence.py
import logging
from collections import defaultdict

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views.decorators.http import require_http_methods, require_safe

from openach.auth import check_edit_authorization
from openach.decorators import account_required, cache_if_anon
from openach.forms import EvidenceForm, EvidenceSourceForm
from openach.models import (
    AnalystSourceTag,
    Board,
    BoardFollower,
    Evidence,
    EvidenceSource,
    EvidenceSourceTag,
)
from openach.tasks import fetch_source_metadata

from .notifications import notify_add, notify_edit
from .util import remove_and_redirect

PAGE_CACHE_TIMEOUT_SECONDS = getattr(settings, "PAGE_CACHE_TIMEOUT_SECONDS", 60)

logger = logging.getLogger(__name__)  # pylint: disable=invalid-name


@require_safe
@account_required
@cache_if_anon(PAGE_CACHE_TIMEOUT_SECONDS)
def evidence_detail(request, evidence_id):
    """Return a view displaying detailed information about a piece of evidence and its sources."""
    # NOTE: cannot cache page for logged in users b/c comments section contains CSRF and other protection mechanisms.
    evidence = get_object_or_404(Evidence, pk=evidence_id)
    available_tags = EvidenceSourceTag.objects.all()
    sources = (
        EvidenceSource.objects.filter(evidence=evidence)
        .order_by("-source_date")
        .select_related("uploader")
    )
    all_tags = AnalystSourceTag.objects.filter(source__in=sources)

    source_tags = defaultdict(list)
    user_tags = defaultdict(list)
    for tag in all_tags:
        key = (tag.source_id, tag.tag_id)
        source_tags[key].append(tag)
        if tag.tagger_id == request.user.id:
            user_tags[key].append(tag)

    return render(
        request,
        "boards/evidence_detail.html",
        {
            "evidence": evidence,
            "sources": sources,
            "source_tags": source_tags,
            "user_tags": user_tags,
            "available_tags": available_tags,
            "meta_description": _("Analysis of evidence: {description}").format(
                description=evidence.evidence_desc
            ),
        },
    )


@require_http_methods(["HEAD", "GET", "POST"])
@login_required
def add_evidence(request, board_id):
    """Return a view of adding evidence (with a source), or handle the form submission."""
    board = get_object_or_404(Board, pk=board_id)

    if "add_elements" not in board.permissions.for_user(request.user):
        raise PermissionDenied()

    require_source = getattr(settings, "`EVIDENCE_REQUIRE_SOURCE`", True)

    if request.method == "POST":
        evidence_form = EvidenceForm(request.POST)
        source_form = EvidenceSourceForm(request.POST, require=require_source)
        if evidence_form.is_valid() and source_form.is_valid():
            with transaction.atomic():
                evidence = evidence_form.save(commit=False)
                evidence.board = board
                evidence.creator = request.user
                evidence.save()

                if source_form.cleaned_data.get("source_url"):
                    source = source_form.save(commit=False)
                    source.evidence = evidence
                    source.uploader = request.user
                    source.save()
                    fetch_source_metadata.delay(source.id)

                BoardFollower.objects.update_or_create(
                    board=board,
                    user=request.user,
                    defaults={
                        "is_contributor": True,
                    },
                )
            notify_add(board, actor=request.user, action_object=evidence)
            return HttpResponseRedirect(reverse("openach:detail", args=(board.id,)))
    else:
        evidence_form = EvidenceForm()
        source_form = EvidenceSourceForm(
            require=require_source, initial={"corroborating": True}
        )

    return render(
        request,
        "boards/add_evidence.html",
        {
            "board": board,
            "evidence_form": evidence_form,
            "source_form": source_form,
        },
    )


@require_http_methods(["HEAD", "GET", "POST"])
@login_required
def edit_evidence(request, evidence_id):
    """Return a view for editing a piece of evidence, or handle for submission."""
    evidence = get_object_or_404(Evidence, pk=evidence_id)
    # don't care that the board might have been removed
    board = evidence.board
    check_edit_authorization(request, board=board, has_creator=evidence)

    if request.method == "POST":
        form = EvidenceForm(request.POST, instance=evidence)
        if "remove" in form.data:
            return remove_and_redirect(request, evidence, evidence.evidence_desc)

        elif form.is_valid():
            form.save()
            messages.success(request, _("Updated evidence description and date."))
            notify_edit(board, actor=request.user, action_object=evidence)
            return HttpResponseRedirect(
                reverse("openach:evidence_detail", args=(evidence.id,))
            )

    else:
        form = EvidenceForm(instance=evidence)

    return render(
        request,
        "boards/edit_evidence.html",
        {
            "form": form,
            "evidence": evidence,
            "board": board,
            "allow_remove": getattr(settings, "EDIT_REMOVE_ENABLED", True),
        },
    )


@require_http_methods(["HEAD", "GET", "POST"])
@login_required
def add_source(request, evidence_id):
    """Return a view for adding a corroborating/contradicting source, or handle form submission."""
    evidence = get_object_or_404(Evidence, pk=evidence_id)
    if request.method == "POST":
        form = EvidenceSourceForm(request.POST)
        if form.is_valid():
            source = form.save(commit=False)
            source.evidence = evidence
            source.uploader = request.user
            source.save()
            fetch_source_metadata.delay(source.id)
            return HttpResponseRedirect(
                reverse("openach:evidence_detail", args=(evidence_id,))
            )
        else:
            corroborating = form.data["corroborating"] == "True"
    else:
        corroborating = (
            request.GET.get("kind") is None or request.GET.get("kind") != "conflicting"
        )
        form = EvidenceSourceForm(initial={"corroborating": corroborating})

    return render(
        request,
        "boards/add_source.html",
        {"form": form, "evidence": evidence, "corroborating": corroborating},
    )


@require_http_methods(["HEAD", "GET", "POST"])
@login_required
def toggle_source_tag(request, evidence_id, source_id):
    """Toggle source tag for the given source and redirect to the evidence detail page for the associated evidence."""
    # May want to put in a sanity check here that source_id actually corresponds to evidence_id
    # Inefficient to have to do the DB lookup before making a modification. May want to have the client pass in
    # whether or not they're adding/removing the tag
    if request.method == "POST":
        with transaction.atomic():
            source = get_object_or_404(EvidenceSource, pk=source_id)
            tag = EvidenceSourceTag.objects.get(tag_name=request.POST["tag"])
            user_tag = AnalystSourceTag.objects.filter(
                source=source, tagger=request.user, tag=tag
            )
            if user_tag.count() > 0:
                user_tag.delete()
                messages.success(
                    request,
                    _('Removed "{name}" tag from source.').format(name=tag.tag_name),
                )
            else:
                AnalystSourceTag.objects.create(
                    source=source, tagger=request.user, tag=tag
                )
                messages.success(
                    request,
                    _('Added "{name}" tag to source.').format(name=tag.tag_name),
                )
            return HttpResponseRedirect(
                reverse("openach:evidence_detail", args=(evidence_id,))
            )
    else:
        # Redirect to the form where the user can toggle a source tag
        return HttpResponseRedirect(
            reverse("openach:evidence_detail", args=(evidence_id,))
        )

openach/templates/teams/_details.html
{% load i18n %}


<div class="panel panel-primary">
    <div class="panel-heading clearfix">
        {% if request.user.is_authenticated and request.user == team.owner %}
            <div class="btn-group pull-right">
                <a class="btn btn-default btn-sm" href="{% url 'openach:edit_team' team.id %}">{% trans "Edit Details" %}</a>
            </div>
        {% endif %}
        <h3 class="panel-title">
            {% blocktrans trimmed with team_name=team.name %}
                Intelligence Team {{ team_name }}
            {% endblocktrans %}
        </h3>
    </div>
    <div class="panel-body">
        {% if team.description %}
            {{ team.description }}
        {% else %}
            <i>{% blocktrans %}This team has no description.{% endblocktrans %}</i>
        {% endif %}
    </div>
    <ul class="list-group">
        <li class="list-group-item">
            {% if team.creator %}
                {% url 'profile' team.creator.id as creator_url %}
                {% blocktrans trimmed with creator=team.creator pub_date=team.create_timestamp|date %}
                    Team created by <a href="{{ creator_url }}">{{ creator }}</a> on {{ pub_date }}.
                {% endblocktrans %}
            {% else %}
                {% blocktrans trimmed with pub_date=team.create_timestamp|date %}
                    Team created on {{ pub_date }}.
                {% endblocktrans %}
            {% endif %}
            {% if team.url %}
                {% blocktrans with team_url=team.url%}
                    <a href="{{ team_url }}" target="_blank" rel="noopener noreferrer">Team Homepage</a>
                {% endblocktrans %}
            {% endif %}
        </li>
    </ul>
</div>

openach/templates/teams/_member_panel.html
{% load i18n %}

<div class="panel panel-default">
    <div class="panel-heading clearfix">
        <div class="btn-group pull-right">
            {% if team.owner != request.user %}
                {% if not is_member %}
                    <form method="POST" action="{% url "openach:join_team" team.id %}">
                        {% csrf_token %}
                        {% if team.members.all|length > 10 %}
                            <a class="btn btn-default btn-sm" href="{% url 'openach:team_members' team.id %}">{% trans "View All" %}</a>
                        {% endif %}
                        {% if pending_request %}
                            <input class="btn btn-default btn-sm" type=submit value="{% trans 'Membership Pending' %}" disabled>
                        {% elif pending_invitation %}
                            <input class="btn btn-default btn-sm" type=submit value="{% trans 'Accept Invitation' %}">
                        {% elif team.invitation_required %}
                            <input class="btn btn-default btn-sm" type=submit value="{% trans 'Request Membership' %}">
                        {% else %}
                            <input class="btn btn-default btn-sm" type=submit value="{% trans 'Join Team' %}">
                        {% endif %}
                    </form>
                {% else %}
                    <form method="POST" action="{% url "openach:leave_team" team.id %}">
                        {% csrf_token %}
                        {% if team.members.all|length > 10 %}
                            <a class="btn btn-default btn-sm" href="{% url 'openach:team_members' team.id %}">{% trans "View All" %}</a>
                        {% endif %}
                        <input class="btn btn-danger btn-sm" type=submit value="{% trans 'Leave Team' %}">
                    </form>
                {% endif %}
            {% endif %}
        </div>
        <h3 class="panel-title">{% trans "Team Members" %}</h3>
    </div>
    <ul class="list-group">
        {% for member in team.members.all|slice:":10" %}
            <li class="list-group-item">
                {% if member.id != team.owner.id and request.user == team.owner %}
                    <form method="POST" action="{% url 'openach:revoke_membership' team.id member.id %}">
                        {% csrf_token %}
                        <a href="{% url 'profile' member.id %}">{{ member.username }}</a>
                        <input class="btn btn-danger btn-xs pull-right" type="submit" value="Remove">
                    </form>
                {% else %}
                    <a href="{% url 'profile' member.id %}">{{ member.username }}</a>
                {% endif %}
            </li>
        {% empty %}
            <li class="list-group-item">{% trans "Team has no members" %}</li>
        {% endfor %}
    </ul>
</div>

openach/templates/teams/_notifications.html
{% load board_extras %}
{% load i18n %}

{% with obj=notification.action_object target=notification.target actor=notification.actor timesince=notification.timesince %}

    {% url 'profile' notification.actor.id as actor_url %}

    {% if notification.verb == 'remove' %}
        {% blocktrans trimmed with team_url=obj.get_absolute_url %}
            <a href="{{ actor_url }}">{{ actor }}</a> removed you from team <a href="{{ team_url }}">{{ obj }}</a> {{ timesince }} ago.
        {% endblocktrans %}
    {% elif notification.verb == 'request_membership' %}
        {% blocktrans trimmed with team_url=target.get_absolute_url %}
            <a href="{{ actor_url }}">{{ actor }}</a> requested to join team <a href="{{ team_url }}">{{ target }}</a> {{ timesince }} ago.
        {% endblocktrans %}
    {% elif notification.verb == 'accept' %}
        {% blocktrans trimmed with team_url=obj.get_absolute_url %}
            <a href="{{ actor_url }}">{{ actor }}</a> accepted your membership request for team <a href="{{ team_url }}">{{ obj }}</a> {{ timesince }} ago.
        {% endblocktrans %}
    {% elif notification.verb == 'reject' %}
        {% blocktrans trimmed with team_url=obj.get_absolute_url %}
            <a href="{{ actor_url }}">{{ actor }}</a> rejected your membership request for team <a href="{{ team_url }}">{{ obj }}</a> {{ timesince }} ago.
        {% endblocktrans %}
    {% elif notification.verb == 'invite' %}
        {% blocktrans trimmed with team_url=obj.get_absolute_url %}
            <a href="{{ actor_url }}">{{ actor }}</a> invited you to team <a href="{{ team_url }}">{{ obj }}</a> {{ timesince }} ago.
        {% endblocktrans %}
    {% else %}
        {{ notification }}
    {% endif %}

{% endwith %}

openach/templates/teams/_team_table.html
{% load i18n %}
{% load board_extras %}

<table class="table table-hover">
    <thead>
    <tr>
        <th>{% trans "Team" %}</th>
        <th>{% trans "Created" %}</th>
        <th>{% trans "Members" %}</th>
        <th>{% trans "Description" %}</th>
    </tr>
    </thead>
    <tbody>
    {% for team in teams %}
        <tr>
            <td>
                <a href="{{ team.get_absolute_url }}">{{ team.name }}</a>
                {% contains_tag user_teams team.id as is_member %}
                {% contains_tag user_pending team.id as is_pending %}
                {% contains_tag user_invites team.id as has_invite %}
                {% contains_tag user_owns team.id as is_owner %}
                {% if is_owner %}
                    &nbsp;<span class="label label-info">{% trans "Owner" %}</span>
                {% elif is_member %}
                    &nbsp;<span class="label label-info">{% trans "Member" %}</span>
                {% elif has_invite %}
                    &nbsp;<span class="label label-info">{% trans "Invited" %}</span>
                {% elif is_pending %}
                    &nbsp; <span class="label label-info">{% trans "Membership Pending" %}</span>
                {% elif team.invitation_required %}
                    &nbsp;<span class="label label-info">{% trans "Invite-Only" %}</span>
                {% endif %}
            </td>
            <td>{{ team.create_timestamp|timesince }}</td>
            <td>{{ team.members.count }}</td>
            <td>{{ team.description }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% include 'boards/common/_pagenav.html' with paged=teams %}

openach/templates/teams/create_team.html
{% extends 'boards/base.html' %}
{% load bootstrap %}
{% load i18n %}

{% block title %}{% trans "Create Team" %} | {{ site.name }}{% endblock %}

{% block content %}
    <h1>{% trans "Create Team" %}</h1>

    <p>
        {% blocktrans trimmed %}
            To create a team, enter a team name, and optionally provide a description and URL.
            You will be able to invite team members once you've created the team.
        {% endblocktrans %}
    </p>

    <form action="{% url 'openach:create_team' %}" method="post">
        {% csrf_token %}
        {{ form|bootstrap }}
        <div class="form-group">
            <div>
                <button type="submit" class="btn btn-primary">{% trans "Create Team" %}</button>
            </div>
        </div>
    </form>
{% endblock %}

openach/templates/teams/edit_team.html
{% extends 'boards/base.html' %}
{% load bootstrap %}
{% load i18n %}

{% block title %}{% trans "Edit Team" %} | {{ site.name }}{% endblock %}

{% block content %}
    <h1>{% trans "Edit Team" %}</h1>

    <form action="{% url 'openach:edit_team' team.id %}" method="post">
        {% csrf_token %}
        {{ form|bootstrap }}
        <div class="form-group">
            <div>
                <button type="submit" class="btn btn-primary">{% trans "Edit Team" %}</button>
            </div>
        </div>
    </form>
{% endblock %}

openach/templates/teams/invite.html
{% extends 'boards/base.html' %}
{% load bootstrap %}
{% load i18n %}

{% block title %}{% trans "Invite Team Members" %} | {{ site.name }}{% endblock %}

{% block content %}
    <h1>{% trans "Invite Team Members" %}</h1>

    <form action="{% url 'openach:invite_members' team.id %}" method="post">
        {% csrf_token %}
        {{ form|bootstrap }}
        <div class="form-group">
            <div>
                <button type="submit" class="btn btn-primary">{% trans "Invite" %}</button>
            </div>
        </div>
    </form>
{% endblock %}

openach/templates/teams/manage_team.html
{% extends 'boards/base.html' %}
{% load board_extras %}
{% load i18n %}
{% load notifications_tags %}
{% load bootstrap %}

{% block title %}{% trans "Team" %} | {{ site.name }}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-7">
            {% include 'teams/_details.html' %}

            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                    <div class="btn-group pull-right">
                        <a class="btn btn-default btn-sm" href="{% url 'openach:invite_members' team.id %}">{% trans "Invite Users" %}</a>
                    </div>
                    <h3 class="panel-title">{% trans "Membership Requests" %}</h3>
                </div>
                <ul class="list-group">
                    {% for invite in member_requests %}
                        <li class="list-group-item">
                            <form method="POST" action="{% url "openach:decide_invitation" invite.id %}">
                                {% csrf_token %}
                                <a href="{% url 'profile' invite.invitee.id %}">{{ invite.invitee.username }}</a>
                                <div class="pull-right">
                                    <input class="btn btn-primary btn-xs" type="submit" name="accept" value="{% trans "Accept" %}">
                                    <input class="btn btn-danger btn-xs" type="submit" name="reject" value="{% trans "Reject" %}">
                                </div>
                            </form>
                        </li>
                    {% empty %}
                        <li class="list-group-item">{% trans "No membership requests" %}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="col-md-5">
            {% include 'teams/_member_panel.html' %}
        </div>
    </div>
{% endblock %}

openach/templates/teams/members.html
{% extends 'boards/base.html' %}
{% load board_extras %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "Team Members" %} | {{ site.name }}{% endblock %}

{% block content %}
    <h1>
        {% blocktrans with team_name=team.name %}Team Members for <i>{{ team_name }}</i>{% endblocktrans %}
    </h1>
    <ul class="list-group">
        {% for member in members %}
            <li class="list-group-item">
                {% if is_owner and member.id != team.owner.id %}
                    {# FIXME: should ideally pass a "next" parameter to server can redirect back to same page #}
                    <form method="POST" action="{% url 'openach:revoke_membership' team.id member.id %}">
                        {% csrf_token %}
                        <a href="{% url 'profile' member.id %}">{{ member.username }}</a>
                        <input class="btn btn-danger btn-xs pull-right" type="submit" value="Remove">
                    </form>
                {% else %}
                    <a href="{% url 'profile' member.id %}">{{ member.username }}</a>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
    {% include 'boards/common/_pagenav.html' with paged=members %}
{% endblock %}

openach/templates/teams/teams.html
{% extends 'boards/base.html' %}
{% load board_extras %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "Teams" %} | {{ site.name }}{% endblock %}

{% block opengraph %}
    <meta property="og:title" content="{{ site.name }} {% trans "Team Listing" %}" />
    <meta property="og:url" content="{{ request|canonical_reverse:'openach:teams' }}" />
{% endblock %}

{% block content %}
    <h1>
        {% trans "Intelligence Teams" %}
        <a class="btn btn-primary" href="{% url 'openach:create_team' %}">{% trans "Create Team" %}</a>
    </h1>

    {% include 'teams/_team_table.html' %}
{% endblock %}