openach/urls.py
"""Analysis of Competing Hypotheses Django Application URL Configuration.

See the Django documentation for more information:
* https://docs.djangoproject.com/en/2.1/ref/urls/
* https://docs.djangoproject.com/en/2.1/topics/http/urls/
"""

from django.urls import path

from . import views

# NOTE: Django's API doesn't follow constant naming convention for 'app_name' and 'urlpatterns'

app_name = "openach"  # pylint: disable=invalid-name

urlpatterns = [  # pylint: disable=invalid-name
    path("", views.site.index, name="index"),
    # NOTE: when running the dev server, Django will try to serve from the static file provider b/c of static prefix
    path("static/images/bitcoin.svg", views.site.bitcoin_qrcode, name="bitcoin_donate"),
    path("boards/", views.boards.board_listing, name="boards"),
    path(
        "accounts/<int:account_id>/boards/",
        views.boards.user_board_listing,
        name="user_boards",
    ),
    path(
        "accounts/notifications/clear/",
        views.notifications.clear_notifications,
        name="clear_notifications",
    ),
    path(
        "accounts/notifications/",
        views.notifications.notifications,
        name="notifications",
    ),
    path("teams/create/", views.teams.create_team, name="create_team"),
    path("teams/", views.teams.team_listing, name="teams"),
    path("teams/<int:team_id>/join/", views.teams.join_team, name="join_team"),
    path("teams/<int:team_id>/leave/", views.teams.leave_team, name="leave_team"),
    path("teams/<int:team_id>/", views.teams.view_team, name="view_team"),
    path("teams/<int:team_id>/edit/", views.teams.edit_team, name="edit_team"),
    path("teams/<int:team_id>/members/", views.teams.team_members, name="team_members"),
    path(
        "teams/<int:team_id>/members/invite/",
        views.teams.invite_members,
        name="invite_members",
    ),
    path(
        "teams/<int:team_id>/members/<int:member_id>/revoke/",
        views.teams.revoke_membership,
        name="revoke_membership",
    ),
    path(
        "teams/invitations/<int:invite_id>/",
        views.teams.decide_invitation,
        name="decide_invitation",
    ),
    path("boards/<int:board_id>/", views.boards.detail, name="detail"),
    path("boards/create/", views.boards.create_board, name="create_board"),
    path(
        "boards/<int:board_id>/history/",
        views.boards.board_history,
        name="board_history",
    ),
    path("boards/<int:board_id>/edit/", views.boards.edit_board, name="edit_board"),
    path(
        "boards/<int:board_id>/permissions/",
        views.boards.edit_permissions,
        name="edit_permissions",
    ),
    path(
        "boards/<int:board_id>/evidence/add/",
        views.evidence.add_evidence,
        name="add_evidence",
    ),
    path(
        "evidence/<int:evidence_id>/sources/add/",
        views.evidence.add_source,
        name="add_source",
    ),
    path(
        "evidence/<int:evidence_id>/sources/<int:source_id>/tag/",
        views.evidence.toggle_source_tag,
        name="tag_source",
    ),
    path(
        "evidence/<int:evidence_id>/edit/",
        views.evidence.edit_evidence,
        name="edit_evidence",
    ),
    path(
        "evidence/<int:evidence_id>/",
        views.evidence.evidence_detail,
        name="evidence_detail",
    ),
    path(
        "hypotheses/<int:hypothesis_id>/edit/",
        views.hypotheses.edit_hypothesis,
        name="edit_hypothesis",
    ),
    path(
        "boards/<int:board_id>/hypotheses/add/",
        views.hypotheses.add_hypothesis,
        name="add_hypothesis",
    ),
    path(
        "boards/<int:board_id>/evidence/<int:evidence_id>/evaluate/",
        views.boards.evaluate,
        name="evaluate",
    ),
    path(
        "boards/<int:board_id>/<slug:dummy_board_slug>/",
        views.boards.detail,
        name="detail_slug",
    ),
    path("about/", views.site.about, name="about"),
    # JSON API
    path("api/boards/", views.boards.board_search, name="board_search"),
]

openintel/urls.py
"""Open Synthesis URL Configuration.

See the Django documentation for more information:
* https://docs.djangoproject.com/en/2.1/ref/urls/
* https://docs.djangoproject.com/en/2.1/topics/http/urls/
"""

import notifications.urls
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path, re_path
from django.views.generic import TemplateView

from openach import views
from openach.sitemap import BoardSitemap

ACCOUNT_REQUIRED = getattr(settings, "ACCOUNT_REQUIRED", False)

# NOTE: Django's API doesn't follow constant naming convention for 'sitemaps' and 'urlpatterns'

# https://docs.djangoproject.com/en/1.10/ref/contrib/sitemaps/#initialization
sitemaps = {  # pylint: disable=invalid-name
    "board": BoardSitemap,
}

urlpatterns = [  # pylint: disable=invalid-name
    path("admin/", admin.site.urls),
    path("robots.txt", views.site.robots, name="robots"),
    path(
        "contribute.json",
        TemplateView.as_view(
            template_name="contribute.json", content_type="application/json"
        ),
    ),
    path(
        "accounts/signup/",
        views.site.CaptchaSignupView.as_view(),
        name="account_signup",
    ),
    path("accounts/<int:account_id>/", views.profiles.profile, name="profile"),
    path("accounts/profile/", views.profiles.private_profile, name="private_profile"),
    path("accounts/", include("allauth.urls")),
    path("comments/", include("django_comments.urls")),
    path(
        "inbox/notifications/", include(notifications.urls, namespace="notifications")
    ),
    path("invitations/", include("invitations.urls", namespace="invitations")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("", include("openach.urls")),
    re_path(
        r"\.well-known/acme-challenge/(?P<challenge_key>[a-zA-Z0-9\-_]+)$",
        views.site.certbot,
    ),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns


if not ACCOUNT_REQUIRED:  # pylint: disable=invalid-name
    # Only allow clients to view the sitemap if the admin is running a public instance
    urlpatterns.insert(
        0,
        path(
            r"sitemap.xml",
            sitemap,
            {"sitemaps": sitemaps},
            name="django.contrib.sitemaps.views.sitemap",
        ),
    )  # nopep8

openach/views/allocate_invites.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from notifications.signals import notify

from openach.forms import IssueInviteForm
from openach.models import Invitation

PAGE_CACHE_TIMEOUT_SECONDS = getattr(settings, "PAGE_CACHE_TIMEOUT_SECONDS", 60)


@login_required
@require_http_methods(["POST"])
@transaction.atomic
def issue_invite(request):
    if request.user.invites_remaining <= 0:
        messages.error(request, "You don't have any remaining invites.")
        return HttpResponseRedirect(reverse("openach:index"))

    if request.method == 'POST':
        form = IssueInviteForm(request.POST, request=request)  # Pass the request
        if form.is_valid():
            invitee_email = form.cleaned_data['invitee_email']
            invitation = Invitation.objects.create(
                inviter=request.user,
                invitee_email=invitee_email
            )
            email = create_invitation_email(invitation, request)
            email.send()

            notify.send(request.user, recipient=invitation.invitee, verb='sent an invitation')

            messages.success(request, 'Invitation has been sent!')
            return HttpResponseRedirect(reverse("openach:index"))
    else:
        form = IssueInviteForm(request=request)  # Pass the request

    return render(request, 'boards/invite_form.html', {'form': form})


def create_invitation_email(invitation, request):
    """Return an invitation email message."""
    context = {
        'invitation': invitation,
        'site': get_current_site(request),
        'signup_url': reverse('signup_url')
    }

    subject = render_to_string(
        "boards/email/invitation_subject.txt", context=context
    )
    subject = " ".join(subject.splitlines()).strip()

    text_body = render_to_string(
        "boards/email/invitation_message.txt", context=context
    )
    html_body = render_to_string(
        "boards/email/invitation_message.html", context=context
    )

    email = EmailMultiAlternatives(subject, text_body, settings.DEFAULT_FROM_EMAIL, [invitation.invitee_email])
    email.attach_alternative(html_body, "text/html")
    return email

openach/views/evidence.py
import logging
from collections import defaultdict

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views.decorators.http import require_http_methods, require_safe

from openach.auth import check_edit_authorization
from openach.decorators import account_required, cache_if_anon
from openach.forms import EvidenceForm, EvidenceSourceForm
from openach.models import (
    AnalystSourceTag,
    Board,
    BoardFollower,
    Evidence,
    EvidenceSource,
    EvidenceSourceTag,
)
from openach.tasks import fetch_source_metadata

from .notifications import notify_add, notify_edit
from .util import remove_and_redirect

PAGE_CACHE_TIMEOUT_SECONDS = getattr(settings, "PAGE_CACHE_TIMEOUT_SECONDS", 60)

logger = logging.getLogger(__name__)  # pylint: disable=invalid-name


@require_safe
@account_required
@cache_if_anon(PAGE_CACHE_TIMEOUT_SECONDS)
def evidence_detail(request, evidence_id):
    """Return a view displaying detailed information about a piece of evidence and its sources."""
    # NOTE: cannot cache page for logged in users b/c comments section contains CSRF and other protection mechanisms.
    evidence = get_object_or_404(Evidence, pk=evidence_id)
    available_tags = EvidenceSourceTag.objects.all()
    sources = (
        EvidenceSource.objects.filter(evidence=evidence)
        .order_by("-source_date")
        .select_related("uploader")
    )
    all_tags = AnalystSourceTag.objects.filter(source__in=sources)

    source_tags = defaultdict(list)
    user_tags = defaultdict(list)
    for tag in all_tags:
        key = (tag.source_id, tag.tag_id)
        source_tags[key].append(tag)
        if tag.tagger_id == request.user.id:
            user_tags[key].append(tag)

    return render(
        request,
        "boards/evidence_detail.html",
        {
            "evidence": evidence,
            "sources": sources,
            "source_tags": source_tags,
            "user_tags": user_tags,
            "available_tags": available_tags,
            "meta_description": _("Analysis of evidence: {description}").format(
                description=evidence.evidence_desc
            ),
        },
    )


@require_http_methods(["HEAD", "GET", "POST"])
@login_required
def add_evidence(request, board_id):
    """Return a view of adding evidence (with a source), or handle the form submission."""
    board = get_object_or_404(Board, pk=board_id)

    if "add_elements" not in board.permissions.for_user(request.user):
        raise PermissionDenied()

    require_source = getattr(settings, "`EVIDENCE_REQUIRE_SOURCE`", True)

    if request.method == "POST":
        evidence_form = EvidenceForm(request.POST)
        source_form = EvidenceSourceForm(request.POST, require=require_source)
        if evidence_form.is_valid() and source_form.is_valid():
            with transaction.atomic():
                evidence = evidence_form.save(commit=False)
                evidence.board = board
                evidence.creator = request.user
                evidence.save()

                if source_form.cleaned_data.get("source_url"):
                    source = source_form.save(commit=False)
                    source.evidence = evidence
                    source.uploader = request.user
                    source.save()
                    fetch_source_metadata.delay(source.id)

                BoardFollower.objects.update_or_create(
                    board=board,
                    user=request.user,
                    defaults={
                        "is_contributor": True,
                    },
                )
            notify_add(board, actor=request.user, action_object=evidence)
            return HttpResponseRedirect(reverse("openach:detail", args=(board.id,)))
    else:
        evidence_form = EvidenceForm()
        source_form = EvidenceSourceForm(
            require=require_source, initial={"corroborating": True}
        )

    return render(
        request,
        "boards/add_evidence.html",
        {
            "board": board,
            "evidence_form": evidence_form,
            "source_form": source_form,
        },
    )


@require_http_methods(["HEAD", "GET", "POST"])
@login_required
def edit_evidence(request, evidence_id):
    """Return a view for editing a piece of evidence, or handle for submission."""
    evidence = get_object_or_404(Evidence, pk=evidence_id)
    # don't care that the board might have been removed
    board = evidence.board
    check_edit_authorization(request, board=board, has_creator=evidence)

    if request.method == "POST":
        form = EvidenceForm(request.POST, instance=evidence)
        if "remove" in form.data:
            return remove_and_redirect(request, evidence, evidence.evidence_desc)

        elif form.is_valid():
            form.save()
            messages.success(request, _("Updated evidence description and date."))
            notify_edit(board, actor=request.user, action_object=evidence)
            return HttpResponseRedirect(
                reverse("openach:evidence_detail", args=(evidence.id,))
            )

    else:
        form = EvidenceForm(instance=evidence)

    return render(
        request,
        "boards/edit_evidence.html",
        {
            "form": form,
            "evidence": evidence,
            "board": board,
            "allow_remove": getattr(settings, "EDIT_REMOVE_ENABLED", True),
        },
    )


@require_http_methods(["HEAD", "GET", "POST"])
@login_required
def add_source(request, evidence_id):
    """Return a view for adding a corroborating/contradicting source, or handle form submission."""
    evidence = get_object_or_404(Evidence, pk=evidence_id)
    if request.method == "POST":
        form = EvidenceSourceForm(request.POST)
        if form.is_valid():
            source = form.save(commit=False)
            source.evidence = evidence
            source.uploader = request.user
            source.save()
            fetch_source_metadata.delay(source.id)
            return HttpResponseRedirect(
                reverse("openach:evidence_detail", args=(evidence_id,))
            )
        else:
            corroborating = form.data["corroborating"] == "True"
    else:
        corroborating = (
            request.GET.get("kind") is None or request.GET.get("kind") != "conflicting"
        )
        form = EvidenceSourceForm(initial={"corroborating": corroborating})

    return render(
        request,
        "boards/add_source.html",
        {"form": form, "evidence": evidence, "corroborating": corroborating},
    )


@require_http_methods(["HEAD", "GET", "POST"])
@login_required
def toggle_source_tag(request, evidence_id, source_id):
    """Toggle source tag for the given source and redirect to the evidence detail page for the associated evidence."""
    # May want to put in a sanity check here that source_id actually corresponds to evidence_id
    # Inefficient to have to do the DB lookup before making a modification. May want to have the client pass in
    # whether or not they're adding/removing the tag
    if request.method == "POST":
        with transaction.atomic():
            source = get_object_or_404(EvidenceSource, pk=source_id)
            tag = EvidenceSourceTag.objects.get(tag_name=request.POST["tag"])
            user_tag = AnalystSourceTag.objects.filter(
                source=source, tagger=request.user, tag=tag
            )
            if user_tag.count() > 0:
                user_tag.delete()
                messages.success(
                    request,
                    _('Removed "{name}" tag from source.').format(name=tag.tag_name),
                )
            else:
                AnalystSourceTag.objects.create(
                    source=source, tagger=request.user, tag=tag
                )
                messages.success(
                    request,
                    _('Added "{name}" tag to source.').format(name=tag.tag_name),
                )
            return HttpResponseRedirect(
                reverse("openach:evidence_detail", args=(evidence_id,))
            )
    else:
        # Redirect to the form where the user can toggle a source tag
        return HttpResponseRedirect(
            reverse("openach:evidence_detail", args=(evidence_id,))
        )

openach/templates/boards/add_evidence.html
{% extends 'boards/base.html' %}
{% load i18n %}
{% load board_extras %}
{% load bootstrap %}

{% block title %}{% trans "Add Evidence" %} | {{ site.name }}{% endblock %}

{% block content %}
    <h1>
      {% blocktrans trimmed with board_title=board.board_title %}
        Add Evidence for <i>{{ board_title }}</i>
      {% endblocktrans %}
    </h1>

    <div class="well">{{ board.board_desc }}</div>

    <form action="{% url 'openach:add_evidence' board.id %}" method="post">
        {% csrf_token %}
        {{ evidence_form|bootstrap }}
        {{ source_form|bootstrap }}
        <div class="form-group">
            <div>
                <a class="btn btn-default" href="{{ board|board_url }}">{% trans "Return to Board" %}</a>
                <button type="submit" class="btn btn-primary">{% trans "Add Evidence" %}</button>
            </div>
        </div>
    </form>

{% endblock %}

openach/templates/boards/create_board.html
{% extends 'boards/base.html' %}
{% load bootstrap %}
{% load i18n %}

{% block title %}{% trans "Create Board" %} | {{ site.name }}{% endblock %}

{% block content %}
    <h1>{% trans "Create Board" %}</h1>

    <p>
      {% blocktrans trimmed %}
        To create a board, enter a title, a description, and two initial competing hypotheses.
        You will be able to add additional hypotheses once you've created the board.
      {% endblocktrans %}
    </p>

    <form action="{% url 'openach:create_board' %}" method="post">
        {% csrf_token %}
        {{ form|bootstrap }}
        <div class="form-group">
            <div>
                <button type="submit" class="btn btn-primary">{% trans "Create Board" %}</button>
            </div>
        </div>
    </form>
{% endblock %}

openach/templates/boards/detail.html
{% extends 'boards/base.html' %}
{% load board_extras %}
{% load auth_extras %}
{% load i18n %}
{% load comments %}
{% load bootstrap %}
{% load static %}

{% block title %}{{ board.board_title }} | {{ site.name }}{% endblock %}

{% block opengraph %}
    <meta property="og:title" content="{{ board.board_title }}" />
    <meta property="og:url" content="{{ request|canonical_url:board }}" />
{% endblock %}

{% block content %}
    <h1>
        {% trans "Intelligence Board:"%} <i>{{ board.board_title }}</i>

        {% if board|is_private %}
            <span class="private-indicator">Private</span>
        {% endif %}
    </h1>
    {% if allow_share %}
        {% include 'boards/_sharing.html' with title=board.board_title url=request|full_url:board only %}
    {% endif %}

    <div>
        {% if board.creator %}
          {% url 'profile' board.creator_id as profile_url %}
          {% blocktrans trimmed with board.creator as creator and board.pub_date|date as pub_date %}
            Board created by <a href="{{ profile_url }}">{{ creator }}</a>
            on {{ pub_date }}.
          {% endblocktrans %}
        {% else %}
          {% blocktrans trimmed with board.pub_date|date as pub_date %}
            Board created on {{ pub_date }}.
          {% endblocktrans %}
        {% endif %}
    </div>
    <div class="well">{{ board.board_desc }}</div>

    <div class="btn-toolbar" role="toolbar">
        {% if permissions|contains:'edit_board' or permissions|contains:'add_elements' %}
            <div class="btn-group" role="group" aria-label="{% trans "Board Actions" %}">
                {% if permissions|contains:'edit_board' %}
                    <a class="btn btn-default btn-sm" href="{% url 'openach:edit_board' board.id %}">{% trans "Edit Board" %}</a>
                {% endif %}
                {% if permissions|contains:'add_elements' %}
                    <a class="btn btn-default btn-sm" href="{% url 'openach:add_evidence' board.id %}">{% trans "Add Evidence" %}</a>
                    <a class="btn btn-default btn-sm" href="{% url 'openach:add_hypothesis' board.id %}">{% trans "Add Hypothesis" %}</a>
                {% endif %}
            </div>
        {% endif %}

        {% if board.creator_id == request.user.id  or request.user.is_staff %}
            <div class="btn-group" role="group" aria-label="{% trans "Administrator Actions" %}">
                <a class="btn btn-default btn-sm" href="{% url 'openach:edit_permissions' board.id %}">
                    {% trans "Modify Permissions" %}
                </a>
            </div>
        {% endif %}
    </div>

    <table class="table table-bordered ach-table">
        <thead>
        <tr>
            <th colspan="2" class="ach-actions">
                {% if view_type == 'disagreement' %}
                    {% trans "Disagreement View" %}
                {% elif view_type == 'comparison' %}
                    {% trans "Comparison View" %}
                {% else %}
                    {% trans "Aggregate View" %}
                {% endif %}
                {% if vote_type == 'collab' %}
                    ({% trans "Collaborator Evaluations" %})
                {% else %}
                    ({% trans "All Evaluations" %})
                {% endif %}
                <div class="btn-group" role="group" aria-label="{% trans "View Actions" %}">
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-sm btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {% trans "Change View" %}
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{{ board|board_url }}?{% url_replace request 'view_type' 'aggregate' %}">
                                    {% trans "Aggregate" %}
                                </a>
                            </li>
                            <li>
                                <a href="{{ board|board_url }}?{% url_replace request 'view_type' 'disagreement' %}">
                                    {% trans "Disagreement" %}
                                </a>
                            </li>
                            {% if request.user.is_authenticated %}
                                <li>
                                    <a href="{{ board|board_url }}?{% url_replace request 'view_type' 'comparison' %}">
                                        {% trans "Comparison" %}
                                    </a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                    {% if board.has_collaborators %}
                        <div class="btn-group" role="group">
                            <button type="button" class="btn btn-sm btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {% trans "Choose Evaluations" %}
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="{{ board|board_url }}?{% url_replace request 'vote_type' 'all' %}">
                                        {% trans "All Evaluations" %}
                                    </a>
                                </li>
                                <li>
                                    <a href="{{ board|board_url }}?{% url_replace request 'vote_type' 'collab' %}">
                                        {% trans "Collaborators" %}
                                    </a>
                                </li>
                            </ul>
                        </div>
                    {% endif %}
                    <a class="btn btn-link btn-sm" href="{% url 'openach:board_history' board.id %}">{% trans "Board History" %}</a>
                </div>
            </th>
            {% for hypothesis, inconsistency in hypotheses %}
                <th class="hypothesis">
                    <div>{{ hypothesis.hypothesis_text }}</div>
                    {% if debug_stats %}
                        <span class="label label-info">{{ inconsistency.0|floatformat:2 }}</span>
                    {% endif %}
                    {% can_edit request board hypothesis as editable %}
                    {% if editable %}
                        <br/>
                        <a class="btn btn-primary btn-xs" href="{% url 'openach:edit_hypothesis' hypothesis.id %}">{% trans "Edit" %}</a>
                    {% endif %}
                </th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for evidence, diagnosticity in evidences %}
            <tr>

                <td class="evidence">
                    {% if evidence.event_date %}
                        <span class="event-date">{{ evidence.event_date }}</span>
                    {% endif %}
                    <span>
                        <a href="{% url 'openach:evidence_detail' evidence.id %}">
                        {{ evidence.evidence_desc }}
                        </a>
                    </span>
                    {% if debug_stats %}
                        <span class="label label-info">{{ diagnosticity.0|floatformat:2 }}</span>
                    {% endif %}
                </td>

                <td>
                    <a class="btn btn-xs btn-primary" href="{% url 'openach:evaluate' board.id evidence.id %}">{% trans "Evaluate" %}</a>
                </td>


                {% for hypothesis, inconsistency in hypotheses %}
                    {% get_detail votes evidence.id hypothesis.id as detail %}
                    {% get_detail disagreement evidence.id hypothesis.id as detail_disagreement %}

                    {% if request.user.is_authenticated %}
                        {% get_detail user_votes evidence.id hypothesis.id as user_detail %}
                    {% endif %}

                    {% anon_or_voted request user_detail as voted %}

                    {% if view_type == 'disagreement' %}
                        <td class="assessment {{ detail_disagreement|disagreement_style }} {% if not voted %}corner-cut{% endif %}">
                            {% if detail_disagreement < 0.5 %}
                                {{ detail_disagreement|disagreement_category }}:
                                <span class="{{ detail|detail_classname }}">{{ detail|detail_name }}</span>
                            {% else %}
                                {{ detail_disagreement|disagreement_category }}
                            {% endif %}
                        </td>
                    {% elif view_type == 'comparison' and request.user.is_authenticated %}
                        {% if user_detail and not detail %}
                            <td class="assessment {{ user_detail|detail_classname }} {% if not voted %}corner-cut{% endif %}">
                                {{ user_detail|detail_name }} {% trans "vs. No Assessment" %}
                                {% include 'boards/_detail_icons.html' %}
                            </td>
                        {% elif user_detail == detail or detail == None %}
                            <td class="assessment {{ user_detail|detail_classname }} {% if not voted %}corner-cut{% endif %}">
                                {{ user_detail|detail_name }}
                                {% include 'boards/_detail_icons.html' %}
                            </td>
                        {% elif user_detail %}
                            <td class="assessment {% comparison_style user_detail detail %} {% if not voted %}corner-cut{% endif %}">
                                {{ user_detail|detail_name }} {% trans "vs." %} {{ detail|detail_name }}
                                {% include 'boards/_detail_icons.html' %}
                            </td>
                        {% else %}
                            <td class="assessment {{ user_detail|detail_classname }} {% if not voted %}corner-cut{% endif %}">
                                {% trans "Aggregate:" %} {{ detail|detail_name }}
                                {% include 'boards/_detail_icons.html' %}
                            </td>
                        {% endif %}
                    {% else %}
                        <td class="assessment {{ detail|detail_classname }} {% if not voted %}corner-cut{% endif %}">
                            {{ detail|detail_name }}
                            {% include 'boards/_detail_icons.html' %}
                        </td>
                    {% endif %}

                {% endfor %}
            </tr>
        {% empty %}
            <tr>
                <td></td>
                <td></td>
                <td colspan={{ board.hypothesis_set.all|length }}>
                    {% trans "No evidence has been provided yet." %} <a href="{% url 'openach:add_evidence' board.id %}">{% trans "Add evidence." %}</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if permissions|contains:'read_comments' %}

        <h2>{% trans "Comments" %}</h2>

        {% render_comment_list for board %}

        {% if permissions|contains:'add_comments' %}
            {% get_comment_form for board as form %}
            <form action="{% comment_form_target %}" method="POST">
                {% csrf_token %}
                {{ form.comment|bootstrap }}
                {{ form.honeypot }}
                {{ form.content_type }}
                {{ form.object_pk }}
                {{ form.timestamp }}
                {{ form.security_hash }}
                <input type="hidden" name="next" value="{{ board|board_url }}" />
                <input class="btn btn-primary" type="submit" value="{% trans "Add comment" %}" id="id_submit" />
            </form>
        {% endif %}

    {% endif %}

    {% include 'boards/_footer.html' %}

{% endblock content %}